apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: slack-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:5PmjiJd7l5GQ7Tl+U/507XS5wS+ti5GoS8SE56MGXHJxwqSxvWe9vkpeqHP7q9n3VkYGuEq87TILYJA=,iv:tcfZU/c3D7uEU92UAv+qWVqJ6OyI+IBYrhv5QnBpueQ=,tag:nWMsTU0QKeLqAmv1z2g//w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bDhXYkFSLy9OL1pva1gv
            U0lyUWtkTXV1dkRSOG9ObkFGVkgwRFJwRGhNCnhJemtxeWVVTGpiaW50MkwvMmJE
            Y05OMlJuR1VySmVNeWxDTlhZdXNocWsKLS0tIDdnZGFnbS9YOXlNSGVLbjV2b0tB
            VFlwdUlkL3RxUTRYRk5HSXVaeXRPOUEKPduYFIsJKfqvxg3NoeGJG5NvcTx9rG3n
            OZIDcOh/2vqVPIeHXjNbi9hzpJTgDiE23S+Ws3WvUP4jx6dnGhwQsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qrj8nkk5wvtsp5j6efhhmru2vdshkyyq8fmllrp3enz23pny43cq8zvt06
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T05:04:24Z"
    mac: ENC[AES256_GCM,data:/UsU6CJi4a5UEhVgWoBFdedNd/l0IW2l3wY/CzP2qGBY3T1GO3F+lCuIAr4F9ZFVIudV8bg2GZHqTy6To0H3NU+YXHV8v5wWouTRqmxuXLrGuP6LxtaOdoxwsKKRaQd5UI5p/oV8T1xe6CeoI124MG0buvVVnriTG+B2w0HiCaE=,iv:N7PmhOcynJ95u/QAeuJouT155dEUjPXsPqpP70qdDkg=,tag:4e3BVVf7LsOu6mqSV0724w==,type:str]
    version: 3.13.3
