apiVersion: v1
kind: Secret
metadata:
    name: slack-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:y+J7jmbRUPqe7GKQpGyjvkF8gBRizLdrR4p9/FU3xNN+9aUX9pm+kpcTSNj3Q5MA2u2z5DAAC2dNviE=,iv:MA7VE9fCGotDJC+SCWHX0PhTeDeYeWEojPcRZCmr7GQ=,tag:yYD8kXet3YTVYzuHvaItxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDJBbG5GQlpN
            U2dRV0VhYS9JV2tQUzRWZy9pTjlHVjltWmE2amxkaDZhUGFxbEsyRURxbTlCZzJ0
            NVUwZ0oyRk9LajIzK0p0S1A5YzhBcGo4TFdrMmhCeXJFK1pwc21CK3FSTlVBZ3E1
            dVBPVjgzU3p4aUVteHpKbEN4L2YzbXd0M2srRHhYUFZ6MEQ4ZU8zQi9XNTBIYWg5
            NEc2bi9mc2xFQmhuRG5CY2s3cWdaVThqQTNLRUxmZUZTZ201bW05UXVZK3ZMSExG
            b3BXMDlzU1U2ZHl6QlpJRXFPTXJUanUxR09Uc2llNTZaa0JpVmtPYWNYV1Q4eHdM
            bzNLeENRdGlXaWFwY0pKdmlLT0h5Mkp0QmwzRGRiU0NNVFRGNkZ4b0lUcHpZK0pI
            Y3ZGT1J2b3JCRjhiOUUvajhyTWYxWmhYZGZKOHFSYSt2dzBNMS95cDIxcDJ5MlAv
            Ym1ITmVGY1lVdWVTVWEwVjB4NFFGdmlpQXpyb2IxSi9LT2VxOXZmZi84Z29PV1Aw
            cGRoTE1RTk10UGUvcWxHMjFydmJ3dElDNWZ6YWl4cmhhZWtLRVZ3SGc5SnVWbk0w
            ak5iTFZUSTBmazJ2VDFpb0IyZm5Yc0ltV3ZJaHRGVC9XTEFPT0d2RHY1VHV6WjdF
            L2hRVCtVOFFKc1RMTENpQ2VKeUJ6MFBSb0lweVBEZDFRKy9NRUxOL3JkcnRUQVFm
            eTJiRzEvc1NQa0dlTGFrelNRTTRucWJIbC9aUTA3eWZXYXpFbklxZVRGM3d2YzRE
            Tlp4V0hiMW1paHk2V1ZUTVFZR1NjODdmQmNvL25QamFZMDhBUnArQld6UU5rRk9j
            QkZWMGRFRlVLbTJ4clZDWTVOOWpnTFNIYzRwOS8ySVFqdFkrRzR3ODlTK0NoTktv
            RXVnOUtXUXR1MUk1MjdYOG5MSTJrd01wRS9pcFVYZTdSY0hPU0dEVWhDZWI0eDBp
            c3Q1cnlKOWNialpZeFdTRk5vTno5WkFGWHcyUzcvTTZLd2VTVmpMMTlVRWtjVXl0
            aUJuR0lEVzJTT2pkT2hnbUVWK3Vxb252cTNhUFpNZmI3SWFsSjJraWVCbjhqakdo
            ZjlWOGRiN1lJWHlIL2llUTUvQzFkVkh6MHRBZ1lxaGhHelBMcVEzK3N5MmJKY0dl
            R3l3dWdSamVvYno5WHlVMWhwbmo0emFrb0p2VDFRUlY2RmlJZllCV1ZNNnY0eGk3
            ODJ2RElLanpSMXBMcVBaQ3dtMVhjQWdJT2hvSHRTTDJjY3c1TUxlSDVjc3cwMVkx
            ZU0ydTR5SWRmaFlHYWc0UytkbkRNZUNCU1FZSGdwRFF6eWVwd3Q0M0VXUk8vblBT
            ZDVPdUs0eGxRU1VkaXk1RTVKZVNDdWxITnd0NVgzdjVZcG1TRmc0dzd5YldpM2Nk
            aG1WUGttRmx5YlB2dUpHYjZVNHoyaW9JbzV6Vm5jK2hyWGZEaU9RQloxV1dMU3U0
            cWRoTUVRK3FXbThzZU5kZ3BYSDF6REsveGVQUlIwK3RDSXJiQ2pDMzZXNWMyeHd2
            Nm84aW50U0R1bmpxT0l2Z2pRRDB3Uzc4UVlwOHJmQnkvQXhveXp2VVdqeWpJQ3Jv
            VDlPc3IvV2VQMGswUkhKd202eFVFb25sM0M2d3VmbEJTeU5nclJFWnZ2ZTNybGtl
            dWVJWmFJRm1JQ2MwUS9yYll0QUhZMVZ6RHVyZTV1TWRKWFVncWlFZTYyeXdYZ0lj
            Y2FncFF1U01xTm01cFAxZWRRSFBFUjVSbGlGWEowY1FGYVZYMEI5Yk83eHlhQ3dz
            d205YVIvaUNnenBmZWF3VkdDdSttZUNYME95WUo2RlBzS0tvQ1pGVGdtdzlDcXhS
            ZjYrQUQwcVZhd1ppQ1hkRXFmMG1jNXdpeFpWVlZOZE1nMEcxQmNsSkpkbXQwZ2c3
            dFJidUNOVGFtZUhzRGVidjVsZ3hySVAyS2JMNGczb3pzM0ZvSDJTV05mSExldwpn
            VXFxWXZiWUJNRWFDUVJnbklhMmhzZ0U4OFFWVTd5NENYWC9xYXIrQ0NnCi0tLSBu
            U2l1aVIrY1N1Q0hIeGU0c0Y2NER2VXc4bDNZWHAzdUw1a09GQVRvUEYwCguYzN+X
            0KbPsvinYhnNZ15ofTZ1IQvyossKmndZhMMLzyXjJ4cqzD4HdWHoZDIJ9wdBoN2P
            5TXnmhkN6/jTebk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T07:35:21Z"
    mac: ENC[AES256_GCM,data:LbOk7bAUyeB/NYGsFoDvqlCxKbh84IUUIw8uySho8QhfHqWiDA1FH6ExZeMqDWVBwV08yKOQoOi5/rAIzlYqJx4COT6nA0zisGvptAAWMpNTFLMvp0x5ujMeeCW/R7kSQ/szLNRivi+8YMsqQoRqN/yajFhbKaydLhJxKZlcgDM=,iv:hwS52M4P5eFbMjnqGz7OnBfM3BAudDkj7EpP5Yscrxs=,tag:fCVIgWKGxYuy7AOmwq4wAw==,type:str]
    version: 3.13.3
