creation_rules:
  - path_regex: \.secret\.yaml$ # Files ending with .secret.yaml
    encrypted_regex: '^(data|stringData)$' # Encrypt only data or stringData field
    age: >-
      age1guvkjxc9cp2593z67tzs8dtr4ss2wncertclj0cvuzarg8gj6d4svw8pzd,