creation_rules:
  - path_regex: \.secret\.yaml$ # Files ending with .secret.yaml
    encrypted_regex: '^(data|stringData)$' # Encrypt only data or stringData field
    age: >-
      age1qrj8nkk5wvtsp5j6efhhmru2vdshkyyq8fmllrp3enz23pny43cq8zvt06,