apiVersion: v1
kind: Secret
metadata:
    name: authentik-ldap-wifi-search
    namespace: authentik
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:4DZ0BYm/YgsebBHCrCKZPaJhwUO3orgyvAdT5pxKk4jTTAAwJS7n/JFisWrOwwScwY75fFWivUXxQYfHN/ZCGA==,iv:PrbBRXn2hzCJguroPk5v0ouAUt/GJhltC7XfNEdhpMw=,tag:CLUz18nQJSL+ZmkGSJFf8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDRUeTY1TTVH
            U25sMzd4ekVzWlhUZlhrSThOVmY5MDh0alNodjNIUDFoZGs4cEQrSmdlQ2hEaEl4
            ekp0MzJyd2lDYkZ1MUozUThKcUFXUDRmTDhiQUYyRW96dEtyS3MrbjZJL3NuN1FG
            OTk3bjQvbDZPdUtib0lJTlFVamE1SjUrTWtYeDFOeUgwalJQK1pnbFoyLzhtSWMx
            ZklyQWlEY01RaXhvVkZjWitmMkxSa1pHNTNYMnZSeUFJaTVUMnpsMytDait6OW5C
            a2dPdGp2eUl2UUdHR09UQWlkaFF2T0tvRW95R2d6dG9VT1A4ekdXTThSOHF3VG9Q
            bUpkQzFwSVp2Y0Zyb0NON0s0VnBJUjlzRDdNKzN1ZGRTY0tuN01ydWxvRUxsVGUz
            NVNkQ3hkWGZ6VCtqR2tpOVlKV1JXR2RNUXpoZndUOXdncWppbkdoaWFqYWhuY05i
            OUdjRzNZcDFiUXZrSmtsNkY4a3YyOGVWN1lhY0F3Ri9HVTZ4TmJVNVB0NHg0Qmtn
            RHQxakd4TFNZRm83NzBBSW5nVTA1UVNhS0NkbWVFV1phcjJDaXFEbnNJQWhFRk5O
            cklEZ010OUxVVVlqdkRtejZEVEtqbG02cEwzaXZkUEloWHlOak53eTNlV3UyQTRo
            bGJzb3lkQklacmhWUG9JMVlIL3BDWE5ldzNGRHZOVGloZHcvSC9ySllsRzJqUWM0
            MFhYaVROVzE3QXQ3UFM4SSs1Z3RmMVBlVFdqKzQvQVdhNyt0QWpoVFdNbzZMejUr
            TDNldXdGYlY2eDlZV2JQZitOYStLTE40a0JnRlYyS1RqYjY2OXYzaVFoZFpZVCt4
            c1l4Z2pzOG9vWVdHZ3Facjhhd3hwNVovdit3ZEVXNEoxRVErUGRWWThpanlFaC9B
            NWlRcXFZSG1oQldwRUx0RFdyZFJOOW5WTkhpL1F5ait4UHJsek5ROVlWaEtOdUdO
            NFA5NUpKQTVab3k0TEZhV1pNTmNIMzd5N2RUckFXeVMrVm4yRGNGSDBwdUx5cnUx
            MXVqSjFURjdreUlTczhaL3FTaUxIRUNtMmt3MHFsQjB0N0RPSzV0MXZEZWZ6S3JV
            N3lMNlNiTk1RQ280bVZJclRSbGtqNDBIL1FFemU1VUpWVUZPdzNxTnFETXNlbUlS
            dXYyZlpXTk5pZVpiLy9oUkR4NHI5MnppWnpTZllnTGk4QkdOMXJiMTdRTldsVHpa
            SjlIaWY4NWRQUjRJOEpVMk9XOGlOWVZRNUI5OC9XUGM5QkJyT1JnMUN2d1NjVHk0
            cUV1aVlLMVVjZjlKWlAyai82K3RrNXkwOGZsS2I5SktKeWNXVzA0QnFqZkltT3FL
            aTBUZUtOK2NLdFBTTnVKVk8wZHFiRVFTOHZzL2JUc1JxWDlzV2R2aHJaQm0vbGM2
            cXlkUDVjWGhiVEc5YWZnejhRT3Q3cWpNTkFtbG1nY2xjek00WGFGOXE3QUxQUDVj
            TE1jb2NVVmEyejg0cmwyRUlDK29vMWpHNUJqR2FjbGFQc2FRMFhuQnRsSmhKb0R3
            Y045a2tVbzhhS0I4Ti9NTTYrd3gwNVMrRXVjMzhOWklvczZGdW5FOHh4U3RrTEky
            ai9rMGlkQm4xT0swcVVFK05zLy9MVlBNdk9ienZGTVI2Q01zUUZSQy9sSk00U2lH
            eWRYYXhqenlsQ0hRSTNFZFkreTRTcXNFL2NNSkovU3pGWm9sVWFuSTVkTnRQaklW
            WmZNM09kMnFITU1waXk1RmFTMUovZDBkazdpRExuR25jdTZYMWpSVUVYbzlRS2VZ
            bWloeDZLZGNrRU50OExwQy9MY2tWQVJCc1JGVlorQkRHemZ5aVdpdUJmbS9UZ0M0
            c2d2Z2lsTndpalVuRWI0cTFxc2E4YUhKcmNHMC90MHhGUHRpODhmbDB1MXVvYXYr
            UVA3dkYwSExmU1pOWmdYeXM2SnJoVkdFY2x5STV1VnBML2lvWnNyVlJadmFPdwpv
            Z3VVMnNvUGFyUlZDWG8zajVTSjRoZEN1emhPRUlOOUVOS0FjSUtlQWRJCi0tLSBs
            bWtTYngwZ2U4WnJ3b0RYTmM4TFV6S3Irb0NLdUF2NlFUcHJpK2xBREZrCgqTHaTu
            HGqQHaazueP0JO9pbn+4cf0zyUhIJA3HJNvSN7PBqVJA/l8Y3xfDeJ4hjiktZHfs
            PdRW3ui52RR87P8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:30:24Z"
    mac: ENC[AES256_GCM,data:RSPOkDHiqqnkSIdkGHp45Dp1xM4+SZNL0uAItAnjr6buNKtigp1VsFc5YSN5Cdjazf0MBANf28AoWVgA4IidSZ1enl1qxAI9C+ah5r4kmZWo8a8t3dRinbhCwpVLLcYmqGSqWm/lWbvC4/7EjveXiviOFLRbUoKaCOKCtwubmo8=,iv:+lhWd+YHS9RiKzqdLd3LMu6KFSFyF9N3AcmQ2uf7rAE=,tag:J96MICQLSxz2EF/Fmq+kDg==,type:str]
    version: 3.13.3
