apiVersion: v1
kind: Secret
metadata:
    name: intermediate-wifi
    namespace: step-ca-wifi
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:B4f7N5XaiRaoBMVAYkYfVFmPY/RHRLhiqU3SOMYJ3AHZmsDvqTM7KfQMjJpKl6AT,iv:hpqagvIwxTwlN8UNRM4tFVXZ1IrBY5DIUbhlvuDE1kM=,tag:gbICvrsqJl+12VblhXn5HA==,type:str]
    ca_key: ENC[AES256_GCM,data:URATnvsjWOWrsqsxg4uVle4StFI/VGzJlNYC95IwCdxertIxgFSK7j25AP4C01v9ENHEeeXEN5NA2DZZQbeO9xqj13dvwXDZNu0aKVXSpWXiBV1Oq68GQ7iHgATdy+x7FkrPdV6XtgI0YNn7FUpgg3v2+GvInoMHQaYyQPGfE+4Bt1gTKeODi3Q0efC+kMH9ClHw7lOTFz78les8liXWZtvDoVuy6PIqfjOrZnJCGAGGT28cIvNz7pImIB18GsP95u4febFHa4bpskbmrkNv9E1BWI7FosuPhu7wN2CD42TKm1Fk8SfKXscXFTSHQ0NUZG5Mwjlrnkfx0M0Cw6LJaklJheMMtaXj7rPOfS0Lcn0ZPCw4Tjqj45EGN6OYRNMW3DazCfhQBMbL1rqpYd0U5/8K6QHqO/ElHJM=,iv:AcY3Q0oRvDmwjJG7SE6PVXotp5dl2mUV1H3wV7zYLnA=,tag:8oPljRlq86PEr03wYNs+kw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGYxY1FZcUFZ
            RUpTS2wrbHBPdkR3R3pjRFVtTmo3SEpycThKOXdYYnQ1d3RySVBCb2ROMzFGRWZQ
            YUs5M3Y5cU1mcjlIanpRQzE5K2JkSVJMRDh1aGVvT3plU2V6UG8xd0V4Q0xQQ2s5
            eU10QVFjL0pLNzUxcUFCYTVGNjBxZzlxKzZZSmhJaEZRd0cwd01sbDhQTHp3b0ls
            WUdzN2dQSW9oM1h4eHd1S3VNemlvVWd2bkVMK0xZK1JyWERjeFRudnVjUHRBeXEz
            TGd5aE1pSzNrQ0xVWGxVd3A1NndKcmxJOHdXelZkelpiemNQVVE4YmVsTDJ5M3ZG
            WnlQVzFVRVdnaFdJTVVZZjY0VTU3NjhPd3dLdm13MXJJUEcwMVd0SWlMZFg2SnA1
            akRObWF4ak1IdWVBOUk0SXJRTFZ4UTA1bFJMOEVDVUdPWW9wTzhJWFJYQ05VaFRC
            NGFjWjh3UWM2RWV5ZXNJaWtmQS9Pbk4ySVFKQkVBY0RScHljaEt4cFRqaWhHNnVt
            K1hXVm9LWXRqUU1UMkpWVWNhWngwRVZGWW5wZEFPWXp3RUtDRUZkT0xnOVFIOE1X
            cE1YZ1lMeE84VUJrVWJaaTIzWWJVLy9PNWhOYWkyZytRV1htZzN6Q2wxc3czYnBl
            N1NjYWNQZEFCaGNSeTUxZDNNNEl4cSs1Sk15MzZIemJqK3ErTk1BdkdrRURpMTYz
            QTdzSURjQ2xWS3R1OEs1akVaNDFaY1g2SS83aHBjektPSWtmV1BwUGVva3ZHNlpI
            amdmdUdqVmw1M3FITzZVSWJuc2E2QWVHTUdiM09SK2lNRkU4NjE4MUdlZjlTVU9s
            YSs0Tnh3R0puVXhrOHBuM2tkWWIwZTI1WFVNMThHUmplQ2dVZ3AzRkpKVDlka20x
            SVBmZlBoVkJhYVpROWtadXEweWYrY2dCcWxVYzZQQjlIQ01PSFJZMFpMeXpURHY3
            RmI5U3k2eitjbmVjM0lWZmtjRmNmcE1DK3NtbEpPcFdudjJDOXBTNkNpRnNPU09j
            Ukp3YjloL1NieVh1KzlrbjZyc2djSHhLSVNpUEk3eEx1cG1QME5wLzB1TlRWM2Zs
            eExSbkVBNC9mQWMvNWRYaXFpV3lmRTdXSjVyRzR1NkRTTHdRcEJIMUU3U1p0enE1
            dDBnbVR4aHU2SnV6M01vQnJCcFRiTmF1ZUx6NlRvSHBrV2FLZDhuaHY0c1JYNlJS
            R2Vnb0d1RXdTRlgrSWFnbTA2U0NLa0RzdzdOZU1nVGNpRlo3aXd5Qng4aTBXSEM0
            MXVZSXp4ZFN2R3dyU2tyaWhvQ0h1R0l4bHpqcVM0ZUtIL2puM0Q3UVhTanN1clJj
            UzRZYVNlNkh6NGQ3N3FSbm81U0RJQVpwb0ZUelB1TUhLbklDck9uUG5VNTZlWmg1
            WFU0dG5ZSEFHald0QWlReFdaTC9aRnF1d1ZrN3RLMklHd1hMWkl3a1lqWFZ6T1I5
            YktQU1lodURZTTd0QTRkTUdOZE10N2lhZmptSFlnT3BnaE83MWNBUUp4MURzbWhr
            SkZtODRGUWRURHRSMEVJT1NWbVg4RXdNTXpKSi9WVUV1cmtjTGJ2SjRGVDFneGc0
            U2JhME9wYUpXbU5HMGoxZEJCU0VwQ1NDNUt5emhpS09SRGx1UXBmeXBxemxXaU9v
            cWZ6UVBwcEdoOFI3cDUvTzZ0T1g1UENqY21ldFNXTWNCSHZyVUI0TXBZbkFoSkpw
            eGFacFp6Rll2Umx1eldYUE9YZjV4SXZXZHdQOGpVaVB3UXltZHRKUWJUTlE5bER6
            bjVReUIzbS9uMFVqZ01hZDk0U2FxbTd4QlQ5OFIrYmxFYVZyVXNlN3ZhbXlTQ0Fp
            eDlRU2E5cW5na1d2QkJVZDlveFJSaGNpYk1UdlpZVWdhNGs1bnlpbkR4d0U3KzY4
            ZkRVcTZsdXBHcTVDOURhZTA1V2g5d21peUtKN2w5OStwOXNENHl0bTljOTRNdwpE
            QTQ5dEhtOXFleWV1SW1TWGcrZ1hHazEyb1VHMFBTV2s3dnFDRXZmb0tZCi0tLSBk
            aGc4M1Y3OHgzRGs1NDBZeVRWc21FZVFBcWJlaGRBZEZaYUFTTzgzbURvCtGzsfDZ
            CZpgOcxJQb3kdWWDD9zp2jUiBVl9wZ9ByKnFA0spSPWIQzmcalk6JBJ51fsIEWEc
            hUoiFpj1K/ys/qk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:05:02Z"
    mac: ENC[AES256_GCM,data:4FRQgD4dbIXL3whZv/6Ac6N3c1GOCIl9a8C/j1Jxy12wmXrn7YKbt7Dd1iYANP6RvUm48EPnIcS4f/Xr0FSTRH8zDiqkTxesVfOUixR85FhcQIn5g21Y8jaK/tfk6fGZtLsI4uiqlKB+R2pdtBO6fY8IMXFO+BvTzrynrTg0Hq8=,iv:S0UPXshQ44fkgn9Mg2gvncpjAZ7qg63uSsot+89AAMM=,tag:qvKtITr2ZDIxaH43sshPYw==,type:str]
    version: 3.13.3
