apiVersion: v1
kind: Secret
metadata:
    name: intermediate-backend
    namespace: step-ca
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:pWb4+oCB1FYE/N5zzzRj2EnfnSxgRJApLHxYIDRhL7w=,iv:pbfbAFCjSjVN6sp26HlPnrX7GoXIq7c/Mww9+fqrYM0=,tag:aORT4TaldWtbFYSfLfmFkw==,type:str]
    intermediate_backend_key: ENC[AES256_GCM,data:Lu4/K3KC5EnOtRNwBxBBmsE5qo2J1+OzI4xUqIsgMnXq4iZHzjRunBx80TVWwP30WGfvAgprJHKGg/z5hmOILEtZx5dKKTu6bIrytzUr4y5yUdlWtiZnkgYhhIUsC10LBNnZ8tZ6LQxjASZQW91UxorjFCLFjqEHs2WxKJRrimh/CPRQg+pzI5kSB+YqQEsTVIwmk1kXbrWj0VoX6Hq3Um5CrJdALR1YVkriziFEGQoBuhni2URFKumVC1sQQ4S4JG5YufcEVpsjYeSDz/3kQzC7QBs8jfrTgfpBFOAO3FiywelnJg+erRD3FI/oAP46A1LBUnSKC5s2Z2yuxnrts3BoXIcAR+INKqn5SaI6gkHqI2HzTFWMGDf+8r/RY4z2iyYG0bX0sKaEfRbgYRolkdVB+jJmqcgDxyn7XQSHQVI/0zvmQe36KO6gNsRNS3dzp5UTZFdt6G/FMvg13ZlnxA3D/jW3cRzTqs1fFJDpO8AA1IYpkncBmeQ=,iv:5QXLW6UPuttkayGpvAUkg+eCuXALIC+xLMnKkHGk8vw=,tag:QOhk/EvPn0YRbTVU6zTA4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHBacDVhejdk
            OGloTWEyWnphekNHR1ZScWFXRmpmOGpRenhKQ3VXUHZRejU4R0dPTk5kMzBHN2M4
            blVOSklWVjVXNWNudEFLNlY2MFdtQ1A5YS9qMXhwRWs1cmVPSDBXSWo4dksrSFMy
            c0RGcFhXdVFscU1pRGt0NFJQU0RYYlZQcjRHVEphWlpGOWxnTXUvUUtMUzdrclRs
            N0lES0ZIUlB4MHIvVFNWbVcxTTk3SE1yN0VVajRKZnlzbmx0bWRoZkgzcFVqanNL
            Zm5ZblRUVVBJejJwSHFKMkVUUGRNNnlvRytuTUtoWEJBTTJNaGRucFZoWTczRXdC
            VFR3QVVobmRUb01VODhTOWVNT0JzRnA1ZDl3dHk3SGNGN3ljTEM1WElLdjJ3UG45
            U2ZqS3VwNlYxN2RNRGJ2MytqdlZGeERXSExoakJWNTFFTzlFOEtQZkNoVXN1V0Fj
            NCswSGZ6RFdsUUowNGZlVVpCNnNIRmZUMHF0S2ZVSGNxTTlISEVOV3c4T0c4cVFl
            dVJsdXcrZURXYTZsY0U5SlFxTWt6Y2RVT1c2ZVQ3T0hIL05tOVhNVGI0QmRMMm80
            S0JoaDlGdGF3WGRYQ3o3azBBc0VBYy9QMTlNYVNzb2RNTmxxK3NMMDhpeVVPSFNY
            d21ZWEk5SFpYdzFpRnQyTkt1SkVFcDVINWxrWW1ERUxpNzR0Z0VjS3Y2UXZ3Wlhq
            M2o2WEFFNWtad2NOWEJnUHF3UlZuREJCNlBacUF5SERNUUQ4RmJKTHBRUFJGd1A2
            WXg5TUR0NVNqd3NaRTl0QkVWbnNwT1JPUWxUaFNqOVJRbDN2UUZ4TklKZ0tDS3la
            UWxOSTdpN0I0bHBaOHkrWVkwdUtLK2tFYnp1VGRqdXl5V1MzL3FoN3c0RmxQaWhY
            dE1ha2dkTEwxRW1QMmtmRXJaYjdFdkNnQml3RlB4eUI4SmlnRUIwRVFRcVB3dE55
            dGhPejg3OEZrOUlOU1dMbURUMXRpSmI4M0p6OUpBR1B3SGtSeXhTUkt2dk40NGJ2
            TXZudGNwV2J4NXpnaTQ5YUFqcEMrS0FMSXpvdUQrNWRZNGJDQUh2Ly9pTGpkNXVT
            eUlrZTUyVkc4eFQycWw2akw5V0pkNzBsakFVeXVna3hoTTcyOXhEY1N6ZXRFbWN3
            UndOZlRiRFBkVXlCREZjVkFZZDVuNmhIU1NHeGxrckk3VzRKU2grSEMyM0dxVzNp
            enpRQ0lBUERnN3RKZVdBOXhLZnIwMWQyZ1kyd1J2czhJYk1iOFZPVEdVNW5PWWFX
            emlPV0xoYmhtQVZoUkhza3N4ZHpGaWR5YVRtakFuU0dVZTIxN09TSitzNm0rYi9D
            Z1J5TXp4SzI2aUtNbk9sc2lSU2NQWFRtblRCdjZ6SjM2ZkJJV1RaSWsrNENXU2pD
            SEZKMEJocmlkUUNPb0taRHJHRXVSL2oyOWx2dUw2QVJEbWYycXlLQ29RSUpPMEJq
            cmx6aHQ1Y2RsMUJ0UzNZay8vMGZIVVNLVmVoazFuOHhOc1E2d01rWnNwaUc3VmFZ
            UnAzRDEyRVg3UzY0cDFzSEFJa1FuK1RDUkFwWEVsRGkrTDJIU2FmdUZwNDdmOU5D
            b2FiYU1BSnNvTWJ0U25pU3gzaDB5cm9ubnhFR3JkK3M1aWVrK2NtMDdKa1FlNFds
            S1p2bWxOMFR3S1RtMVBJdGZ6T0Yyc051UmJZOWFwOFJpOVRIckI0QmtOKzJOeHR1
            c244cXpCUTJGSWhHTmRMV3BCU2dNM2MyaHlqUUhiWlpxenJGcTI4MHdjUmVRZ1lz
            SlZWcW9CMWxhYTRRVnZ0SXF0bThKV2I5TFIzRVJTZ1RUamhTaVYyK3RzeWp2T3V2
            SFNGcElUSi94UVRVSE9kYVNrcm9uZjl2NzB5cU9teG5mMDVYUEVuVWczbHMwaU9N
            c0cva01EOXlmcThOdXFzMisvYVEwbTNkYWNqY3FDSDFCdVFzYUNyc1Jia0RSUQpD
            QVczY2VwVzVacDAxbFp4NmZHQ1ByK2ZkT3Z4UUJrSHpzVkRVeUZaSGY0Ci0tLSBx
            VStzNUxwRzVYMXZPenFuemlYTDJaMlhBYjBaV0FjUGIyZ3BVa3Via1I4CjV2ODkB
            g0D/DAzxxhE4zjat31hmRYlFmGzmJbWqlplNW6rVwyki4vhE22XQzCk//NIGIQ6j
            2pbOnm8J8lPZ63k=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T12:00:13Z"
    mac: ENC[AES256_GCM,data:ECeARbLNvGTF/aKzk+SekEyzsFRlvwm+IMToS6yfL0F89dPBEX9ua0O+oVZrWFZF/A69Rz38lt9obNYFFP2ey4t+jPXb9Y7jw24hDqR8PXa4+g0+nIZiHG6n6tBNNybxpPbMd2FDdZsqaCKstUTKlEIgx6Ontba7mEP584ChlAU=,iv:zt4qfNrArCOiG5l5sRI0R5eLNR7ROHWUaTmns39qPN4=,tag:Qq5UG8qEF7cWFQq8Yylo2w==,type:str]
    version: 3.13.3
