apiVersion: v1
kind: Secret
metadata:
    name: gts-secrets
    namespace: cert-manager
type: Opaque
stringData:
    gts_eab_secret: ENC[AES256_GCM,data:wnV67n4Mq6+VefiI2YaUpzoYe+BdwnqvUzP1rKg7QXhj2AnPwrSvcUaA5xmlrRbI5NyHvUYiv6rUmsUMl14xt7sIXXkn297kejEOo1imeg1ijLjrjWSE,iv:ZxENELTnzqFW/AA6MqkjP+ghkDmeZPbmObkKAhsimzM=,tag:5XeEgxx+mMZl7Ey0ycXxRA==,type:str]
    gts_eab_secret_stg: ENC[AES256_GCM,data:cGOsXICMzt6xqKK0xvb+9ig5XMKvjTjPcn+8cDWpqT0KDlPdwZJchxVmk3/syEIgI1k3sZdzaPvnFnQMoBzlTa8A5pAHAEDMclLmsZEygUb9V0Pw1IZl,iv:wzfryYZY2qBvQP122fBAxtje0H69SJpJ/yNGIkvq8k0=,tag:wG2RkbZ/lq1PMKo33IzvoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEh3TEZqNmVr
            MFlVOWs2SG5vRTBuaXZtUUdwTjhVSjIxMTE2OXRwYis4ZmJ5eEQ3am9ZQlNHQkFM
            UUJqMGhvOHVoTXVaeXJYbHpueW9rWUUvdE5mUEVhZU02bFdyckYwd3ZpU294WVlD
            enJiK1Bid2RjMjNkS1p5T1REb3dqaDNFQWU1WmNSZlBWR3ZFanh3V21ROGNwbjlv
            S2kxVVc3RlNOL3gwYm02OEpHR0ZaMWxEOWszNjQyU3VFRDBVeFZzUmhoV1NWakR1
            V3RKbTlWL0lDMXFGVVRXVVZvZ0pZMUt1UllWQnRabGRMMFdUeU94dzNVdUliWXZF
            RTlVT0VCZnYwaEh6QVR5aEFPMC85dGhVSldPdi8rNjZQd2o4VjNXQ3o2VS9pak1H
            MXM2Nlp5dlFNWmRPL2NPY0pXL3hKcTV4eWcwcmFpcmtSWFdGMkpEZHZsVmtONFNt
            K0ZyZnl4UGk5L2ZPSjdRUHo4Wk5GSUVVeHZQL214NElYMTZ5dWRqb002ZDV6YzNM
            TnN0NzMzczBQaVVzanBZeDNtbDduL0Y4a2xPdmxjWVZhaHpLVE5DUHVJOWlRSWdP
            WUZRU2JIWU92eG5MQkhGWkd6SjFHQjRKSnV0TjNGQTJlTTJXUGVmZ1g1ZHZITGNw
            ZWZGVnpWSU5BcHRxVmowNVVVT3o3TTdVcmRiZnVHa2xwa2lLZUJDdGxlQWhISEZk
            Z25SYmkvNUVtbU5uQVJLYklRU0dmRHpXMWFja1d6cDB6R1ErVlpjSEZTRUlBUW5D
            YmlmZDVwTXBKS3g0Zis0aWxOQitMbGhBcm1zbGpXekROWEIzU3lvME0zNlRxbHBN
            eDVCcW5KbE1QMk1uZmNDTm8rbmE4bkNtcjM4TzNIZ0tFSHNHaHV6V2E1aW1wSEZj
            MWRrZkdwSTYxRS9tODQwWDhXcS9nYjRFclZqb1pWSGVnOWd4MDlxcmh3aW96ZEQ5
            aU5GZnc4Vm5pV2ZYQmRCN3NwL0htR1Y0aFJDYmQzRkcrZUQ5ZkJQcXk5SVdKc1FF
            TmxLS2NaNjhKRW9aVFVvdlZjR0JPQ0tIRkpTOXRsQWFGNFA3MnhVc1djNXIvWGcv
            c0JsRWIrZEN0bXpTS0lQcXo2NUJvRkpDbHBDa21lV3duZGZlc1NidXdKWUovUzlQ
            UEtzdHdvU29pb3lwUnh4cUJUU08yZmhOQmFxVVE4dUZmeXNodlJPTXptUTVXR1U2
            L3c0Q1F5bzE3Wms2N0l3WWZQQUtNa1libFZZZFlha3FGemlrNVNqQmZ6cisxOWwy
            ZWpMTFI0Y04ybFJYQ3hOa2Z2UHRtbVNORXhXZkxjOTQ0SlQvU002dEtVTFE2OFVj
            WnhGOGh1MXh2OWFwMEwvN28yVkZrRHh4azhIRmk4TUJTaVd4V3dDY2JENDNpVzlL
            a2lnckwrLzNET1lDVUIxOGdybGU5ZU5RUmpYS2xQOUZSdmpQRnVod3dIeDNvVm95
            N2NJK3FZRzRSdFord0J6akQ2R0xFTGRzQTNYQTdNS0luS2tOU2ovTHJlRXdxVFYz
            Wm1sTGJmN1gyL3lmWG9oOWp3dEpnT28wNDZVSW1MWVhERWtENFhIYTlWTTJ5SUdq
            a2xMZlVCYVF4V1B5VVZGOGl1M0VnY2VxRDZoWlo3UmF1ZERaQnZFZTZYanNFNG9w
            Z3g1QWgwbDYyeFlOa3NJWWpTa05DZWxhRklBVXFzU2pHZmR2aGN4b1djMkx3R0h4
            b0xtc1pqRUwzTHYzZXd3d05WaGdwNDVja1Q2bFNFRGNiYksvb3ZtVGhZQXJoejRL
            VVdmZ1VZaEhnMVRVZmt3Y2Z6dXhjclZid1BDYTdCb0RxZU9Wd2paNUtvTERycWxC
            a29pRXJZcDhKRVBpUkJEVnMvZ09jS3lPWk0rT0RHeUZQOGovaUN1Y2FTR3dqZGEy
            bEJwd2VnVXduWGh1SDdCdEZONEl5TVNmbmI4c29abGo0dEhDdm9LSk10QVhMdwp3
            TkxoZERFYlBFaXk5NVM5cWI4ZGxtL3ZIdmdkbXEvbXJPUzJkTEJHOTB3Ci0tLSBz
            clBMdzlXbVpRUVZoMW9lTFhCek05cEoxUTZxY0s1ZHNnZ3dCamZNektVClu4lOpS
            o5Iz0Nw4i3frEnoGX2/WaNTZuVBEX/QtUM2iWU79aNbab7wY7F0kUWmNzmjMPPV2
            Sn7gXz4odEG44Oc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T06:08:31Z"
    mac: ENC[AES256_GCM,data:eCADdHraidchPpRFc1eWB2mj2vnizcj4StDf34t1yOAyC5LN41Y768ckns5aEiUxGZwcQUx3X8+9tGzh4c6gppDTsmOGq72KYKXakOFVAwP1jflA3j4nFDf2zZH8F0ilwb5WiKZZE32n0vzYrFVhGsMmnDgLF5QXS/KLwnJNb/M=,iv:MLhOFuCYeWj5XsIVQuPSetbgEcOiKezCYkrcNi919yE=,tag:4x30uqsFwx3z70EGx40YQg==,type:str]
    version: 3.13.3
