apiVersion: v1
kind: Secret
metadata:
    name: gts-secrets
    namespace: cert-manager
type: Opaque
stringData:
    gts_eab_secret: ENC[AES256_GCM,data:RQRt37ec0p5LxbHfFeAyRIAZlkfxd5wu0aGjBC1GdGOPtMsjzdJq3qzDt4gb1/Loic/VAL5WOX7TO1pw0eIQbqWqWJsUsQ9yVHkcJrVRKIVNpWjvYxeX,iv:6XcI0RPE6iHjspjXcxkRgX/otC9OBXeD2ge3oPgq6Do=,tag:/lf+Ku10upP+nHhJDNFL3g==,type:str]
    gts_eab_secret_stg: ENC[AES256_GCM,data:bE+eRPNa+ZM4goSeDuEbvhUXFoPfS9Vt3zn7/zdvtsRIqQ9B8F/GCeAlSvDNBgLFQ8gXa9kvzA83x0FUnmgC6LmCeHO6v46D07m/FsuSpwzwPgbgL5qh,iv:vrnfTFacPEYYuXFAmoqQegdDhdCZV9qppyrU6RO1cxk=,tag:H1I2IAl8I5GhKz04ZsFPDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc081L2VqODdURG9YR1Zl
            TzFrQjlRckZjRk90Rld1R1YrZnpOc2ZoNnhBClFERlpJZm83UGF4eGl0T1czWGlP
            K0w3NC8yd2owL0poa1NSRVJNMFM5ZUkKLS0tIEF5N3RLZEpMRVkrMEYyZVh4OTJE
            R2hTWTN4aGdoQVpJd29xQ0FNeDJpYncKvPEr8J9bsdCEFi0wgY4t+6h4qQ4OSLW8
            1KmTScHLcavj2iipE207u751pzZSR0m/6j+NsIrizimNnIDSQkHZeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qrj8nkk5wvtsp5j6efhhmru2vdshkyyq8fmllrp3enz23pny43cq8zvt06
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T05:04:50Z"
    mac: ENC[AES256_GCM,data:dgSVr/orwH9P1LN0ve5bfjrpNBVDH6iKo5IEyDwU8Y082H8v6+xzwHSER90IqFIezcaTU0PQ+xJCU9IjnC5SQlxpv0Bj67AEatuSkftpmJw2ghB0PSF5PNhBb85NQ3VOCYyD+BJLczxLwXiu+7Ix7MHlwtZHqM6RKWHT+beTLOw=,iv:N/jckP3XBObK1izPZ3MW12JKHIi44eH5yZQkWbRtLMY=,tag:L6/JHw4vvH542mP+h2GpVw==,type:str]
    version: 3.13.3
