apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
type: Opaque
stringData:
    api_token: ENC[AES256_GCM,data:k021u2bYMgfKP5MRDJarbzTgkDcFfMlN+odiebj7EvLGJ/N4PcAmovKTJTH1KvkdtPYSTUA=,iv:NCUTQlScoCbBOU7zF8Yao17sQGszJfzbiGeI3OVjGfE=,tag:YBRKR6mAtfqGvCspoOCiEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb1p2aUNwK2dFYVNCejhk
            TUx3czNjWTZHbG5adEw4YU1YZmIxajlxakRJCmt4cnREVXFWa0V0MHRtZm54bGdL
            WktrcTVkT2J4QVdwM3pCTUZSQXJrOFEKLS0tIEN3SC8vMlhFenBrMUpFZFdGaFMv
            Mmk0OG43Y3FVcjBaSjF1T3JWK3E3cEEKhD9MFPeDYfS8ZCHBMYr9CkRFwtz7MKWA
            Wfl/uMubZ/7rNrJiVAI8AYJ/HzxSN8DHEiDQBKFMojyj5kEuhXDeCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qrj8nkk5wvtsp5j6efhhmru2vdshkyyq8fmllrp3enz23pny43cq8zvt06
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T05:05:07Z"
    mac: ENC[AES256_GCM,data:EnVl7XgP613E3r6TnE4Vs5VQqUICgPVv/vJ6qcfN7UOsUdfOIgFbDFwUMS9YLgfbkZet1E49UhlO0+R7Sw+Bs1SfnIpGHpKWqK2z/pw6TSQq2mtYumieGeP9yG/aTNPcmlXwyk241sskqs26QmiJBxiYLSCgj5NkVFMP9bEFuXg=,iv:BF1+AdjzDUNVao7rLG9ytbgnwO9QlGTawEqZ5q+a5q0=,tag:cPL4aFcITT4MsHW7iOwx0g==,type:str]
    version: 3.13.3
