apiVersion: v1
kind: Secret
metadata:
    name: cert-manager
    namespace: flux-system
type: Opaque
stringData:
    acme_email: ENC[AES256_GCM,data:yvOBF1aetxI/tZ6b0D8wQXw=,iv:hlHc+mu/67wDgzMAujT/ymfddVn93krG8y/ctcUignc=,tag:eQTDiB0wpXomh+BqSPmc0g==,type:str]
    gts_key_id: ENC[AES256_GCM,data:laxy6WT0WfDjsDaZOWqyOSWvIobEQPLQhJ6R6qHuxPA=,iv:GXvrxYCIL+ZIbKJROz8eSl1xGKkFf+XhhpNrqpKYuhQ=,tag:dIQnkamfgDZmf9wQKK6yeA==,type:str]
    acme_email_stg: ENC[AES256_GCM,data:xbCYFFneRzvnxJH93pH4EEI=,iv:3zDqvmdBlHXjIkP9DnPmPqj1JJXjpm7y4LnQ0C/GumE=,tag:g5XxRERPNurUUOYV8++jVw==,type:str]
    gts_key_id_stg: ENC[AES256_GCM,data:e/WKEb2zdTVqYCUfaZjVEVlKovvkwAkis03CMIk+kJk=,iv:hKWmgljREMBHtZdRvugEmyX19Gqpbv3Y7NiUS1tZEJw=,tag:A0Ut7IA9tGwuDyN9BZ7d7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJ6UzB4WEhm
            cnJuTzB4TFFKUFVUS3FrK3l0L0l5dmlZV216K1lMOUxlTFh6YTVUMzhkZU5XMEFM
            NWJkcVZ0eENMSHVFY1FyaG9LbEpXdVByUGxqbEpJeDZCQytpZGxqaldRTk9MUUtK
            cUx0MlA4UTZnV24xdTFWOThaVVJNcHY2NDNjRElZMDFaUlVYVG1KWFhTdGRpSkFC
            anp6K3EzMUxGbGRmNmo1WmJxcFoydC9pY3VvbzNsOUsyVGw2UEc2R3lweVlrZEZr
            SnYyRjJDNU01aVNXcWYzZjRQS3JGT0o3RVdYWEg1blhKSjdmNGF6eUZJRlYvYWVq
            aU5HOFdVTDMxMTZ0QktPTlBCcTFqTHZNM1Vab1VPK2hvUk8wbkt5eDhoS01DNFFh
            Ni9YZjl6citzcHJkNVQydFlkbXdYSXZhWUFYWUo3KzBsM2FvZDZRZUhUVkFwR09N
            dDBpTEttaDcvaE5ud1lwTEVrSXNpZWRQTk03Zmp1ZzhTMVBIOThvci91UmR2WENQ
            dE5aZEx6aCsvZGhsejBxNEtCYzIzclArdHZHcTZ6SitFbkJZSDd0R0l2dEg4eXVR
            a21VR0FNL1B4SVpXL20rSE1qV1FuZmYvaGhQdWxZeGJCc2ZxUEJLMjhZdnkxTkM3
            UG1VQmR0L0NKcVNYaWpselVkbThlSU9iYU1wTVpkMnVBamNjUFU1YmV3WXIxeHhq
            eTdad3YyWVQxVzJpM1F1eHVXS015V291OGJWYlRGZGw3OURUcFVrNkNvUDRwUFhC
            d3BnYkdEUGQweVdSU2dJcEgrUEhOMUEyVkR4RmVlVU1UQUZZRTZqSElhV2JUeEQ0
            ZzhBZDRHSkdVcEx3NE9YcytnODlkMTIvZVZMNEdyS05JWWNTSS9FOXdHVDdTeG81
            bENSbVk1OFc0b3RrT3E3S0Z5ZXJyZGZLd3Fhbm9MbFlHd05aRzhldTFwaUFjQllE
            ditCWTUvYnQ1L0ZuQ1FqWWU0eGFnR1FLZGtSZFBicFcrQUZLRDZNQ0RHMDg5NEZR
            RytiRW9nY3JXbFMrTE96VmRoT1B3OU5BZVYwczloVlozN3lmUjN1eGgxK3AyWDVW
            ai9HVlVDZTdVR0o0SmZqandxQThtSy9kRFF1UDUxejluODAwVGxPcVU2TFBDUXdT
            cW0weDJHS3YrUllGRWViMUJweXI1SVdnRFVXUHlId2MwNUNsRDh5YlFqOVlBbm5D
            WjZMQldTcVd5MWt6NmhJM3hiVE10cGdoS2x3QUNIZVNSS1Z3YlBZTnRlZVdubUd4
            UERXMG5CWmp0RCs3aHd2WVVUT0JISnZYQ0JuMG1lOU1Ta2l4NnBMV3BjTS9oUmVG
            Y21CT043Z2ZRUXgzbDZoRktWOW5GYTMxMGh0NHJFdys1dHY2SWYrREF5blM3VXNt
            UWJJbStFeGdPWXJOcmZaaXVYa01JZ2dnd21Dd1dCd0luRHhSYzk1SHVIS2wvNWFt
            VVpBODUrb0hFVDg5NXRzVWlheUVoZzdnaktMcVgrVE5teTVocFM5WVJNYldUMlUy
            UnI4K1VHYnBJbGtqc3NQS25WWklyem9SMDhLWkpURkU2TEk5OFMwWm56VXdkckdY
            RlZuT1dlbnZTVmw0WVNVdU8wVHZIVHIxekdhUSt1cmxTcENlMVFSNllSR1pSeCtH
            VlpPUDNocWV1Z3I5QXVHUXZpUEhyMHN1dFhacitNd1RJUmJLNW5abjlXKzgzY1I3
            SFRCRXhDLyszTUJqdWhzVTZxbkFmL0U0K095MGtKdlcvMXkzYXJpb3FuK1hUeUFG
            ckxlNFJnZDJ6ekhBd3Q3d2V6UUJQL3lqMDh2aXFZSCs1K0VFK1RSaWxMN0FjNVc5
            TU9HSERzWis2NmxqRmMyUSs0UW5XQXhiR1NRWSt4a1YxZzJDUjhYc2MwVHVSOVNS
            QU1mRzFSTW5nV0R6YmpMZXdWS1BxM1p4eXNFY2JlSmo2VGJlLzZtZysycExOQQpW
            Q1hhblJqajBmTXdVV3h0c0JNQS9xOHdwQWIxNUlKSjVmMi9CV0QrU21BCi0tLSA4
            dTRBQmlJbGlTb3V5L1RBWGVQamdjUmtsSG9sTTMxR3NQWlpRMEpTakZrChSTCr4n
            BS37HCU7FOhaWe7hFXCBvo5EWDXcEk4mpvkKcrF5dAVTmL9XNZhIRH8ZKvzjnbGq
            u/wLv6CtjOc32hE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T06:08:55Z"
    mac: ENC[AES256_GCM,data:4LlNrZviTFIo3csGKf2il3o7jUipS03eOug/maLg3i1gi5d0nxQfuwdTg6SoP+nMXG/tB682DydbSMxg52yKcz+lsxd+poajymG8RylFydQ/Cis7eben3q8jd2pcCdqJrOJMhoul8Wj6Z/4qswZOP/Y44xkqebwQeh6g9xzO2+Y=,iv:8PvbkhYfp321Be2NWiDa7lUT7J8KK2dZgzTZy3gnpho=,tag:Q8aPk71bJ2WLrkIsxYfVdg==,type:str]
    version: 3.13.3
