apiVersion: v1
kind: Secret
metadata:
    name: cert-manager
    namespace: flux-system
type: Opaque
stringData:
    acme_email: ENC[AES256_GCM,data:5aaQo02WYvoabBtfpQc/aDA=,iv:sSQQPTdbv28KZILU9ounTZYbygCpro2k/O5Rdt6nZQg=,tag:0udPEyYcwbnQdhmRwe+9gQ==,type:str]
    gts_key_id: ENC[AES256_GCM,data:zEKYLR02YwAR4xIiPEfjgdl3J4wzNhz5Qv/RZsDhCA8=,iv:IK1LRn3TL+QBc5CpVYosWNmy/YgY1Qkr123os2Fd91M=,tag:7G5nxMrSdHSs9tZsKv//rg==,type:str]
    acme_email_stg: ENC[AES256_GCM,data:QgHm6JxCCfNGf4ZARRm1tDY=,iv:7Ghu/q6xYEdS0MqAD2SZl+ilLSm8uIKsCXmDD5fLrec=,tag:VH6Y8FllZ9s67Ru20w2cIg==,type:str]
    gts_key_id_stg: ENC[AES256_GCM,data:08o5YKgl3jDVfZ/na8OG5lWXguUFdfsSBpiCSHhMpH4=,iv:po4No7P5PfgO6iUsEzRXZ1rupMgVm89CTOZ04yLRQ+8=,tag:1kCgNs0DkpqWp+8fw8bcpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U0NleDJpZmM4ZnhKWXNm
            c09lMWlKK1R3SGZYbThLY3YveHhpOHJzSDJvCmxDb1BvYnhLVCtwMjNIbjZJOWN1
            UWk0cE4vZXplSW1MSHRCbkY3WDc3SE0KLS0tIGxqc3l3cjZHKzVtKzZ4UXZhalhT
            NUo0VEVHMURnMy9pOVRVS0ROa2tCZEkKTWY8bbxRJJtJLsctR4HEETN0byTxO5ph
            CAR4Jnh6MmjLnocCRpQP8N8AHJCUwbVAF0fhhYBWt4TPEAndw8q3Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qrj8nkk5wvtsp5j6efhhmru2vdshkyyq8fmllrp3enz23pny43cq8zvt06
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T05:05:16Z"
    mac: ENC[AES256_GCM,data:GoVAP0vWePIkpGbjQlx6Az9oD/8ZxXr2s+Ujm2H0sDJ/vbLpuakzTshggBPhWEKncdjXUvRHHr+0u+CLxMl902P/UX0iuQd/lb2zJG6voFZWsFj76JxyCABlNPF2N8kPvidOUSDAIXw/d0eHC59Lm8Y0h+QEZ2sXbNNZz+mKJf0=,iv:BmLn+ysPZ0o6l25CvBaIXg2NaWDf0HWeGSdG8lJ1+D0=,tag:Jbfvl+OK6XimbRAuIoUxAg==,type:str]
    version: 3.13.3
