apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cloudflare-ddns
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:+tA3mAP9plHr710Z7igtnO7zOEaZQWe2eEZcDAjdzRzebR2QdhSpFVjCl+5L8hBqIaKY00o=,iv:AjAvrBO8HZ1uuw2hiZXRgvIColfkQy1ULEgFqd1a9iE=,tag:t17qpgJlPK2vAHwmKexA4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFcyQWtCVm1n
            d1liZ0lzZ05wZzg1YlRWeXp3YlBtbDQzRFR0QUJ0S2NZRFMwdkRxdUsxTjVuMUVS
            M1l3S3lFbjY2UVcwT29GOGJkWlh3aTUrNmZpT0JQQmRMYUJ0Ukd1ZVhPZytEK1U0
            ZWowSXhsZ0psQVdCNE1SK040M2NsMm1JdDMrLy9YUUc0cHRhSDFLLzBMUXZHdTlQ
            TU14NUkzZ1l4QVNIdE5GYWdNdTQrU09iU21VQTFsUFNFSXdQK1RtdzNmWUJwUVhM
            cER5c29TSE9NRTllQWozTWdicU44cTlmRC9jNmtrM2F0bVhGNlUydmYzTHNsempH
            NUtOblhWN1B2WHJLbUF1TTArU1orU3VXckxMV1MreWFpZ04yM0lodVdGT2pRU1lO
            RUVMUEVIdmsrVDRoaDVJbll5bWVvYzRPQWQzU3JoR0xZVkwyckZXR0xnOEtwN2xK
            OG1pdTB4K2xXZWY3MVBsYmNGbEJUdnBxU1lzOVk2RERYeFZmeFIyVEVrdi9rV2Jt
            T0FHcjRidUhvaTJTcVNib0VqdGNEWkJDa2N0dkc2N215ZG9EamtzNnBkaVFhYWFC
            ZlpIM2tlNFNtWUpOTjgyeGJMdjdWV2swZlNtKyt1dVBFOWtnS0JaUnlvNkxSU1Zm
            dEdYVXBPTGljV3lzMzRoWFYra0MrTldHT0toN3VWVENzQStxSUJPV3oxVExIckN4
            NnZEOG1NM3dzVE5jZE12b1VlczBhU3dFS0hsVDUrZ0JqYmhVN281aWRVMkZPSk4r
            MFYwS0hHMUVTRzhCZ3Q4cUZqWUMxYlNyRGxKaXJ3NXREV1luN0RRMTdmd09Ua3cv
            RENkT25LSDFqQm53N3g4bGVOcHdSWjRNM2xrdW9yenNKTkY3UC9kb2NJVUZOcmRV
            alNOMmFrMGpiSUFtQWkzVE5PTnpaSm9yWU1ubE9yRmtXQkYyVGpqOHJHWXRSRDVH
            dy9pK1pvYXlsMHNYSDIyQ1UxUEhMUksvUGl4dnE2Wnl1aXU3NkNkY3hUejVOU2xi
            M2tsWXdtTjRDcXA0cUl0UDBtQ0E1TWdicDNXbVV6U2JLSERTZnFKNENObi8xaFFP
            cWd3REs2SW02K3BEZ1F0KzhrUjIxOG9YKzB6dWRiQW9MelFUbEk4cVFBakl5enFG
            b1RjVEovQ1l2bW5HcVdJOWRZaGRWNXdhbGxVaXFBa2t0NEdWRnRiYXgvWXNwV20w
            VEFqNGl2MEg1anBEcWFGdG9wRHgvVzRtRTZrTDNEYVM5WGFrNTBTZlNSR2ZXcFY1
            eEdpbjUvS2ZNc0k0NGd6RUsxQ2lTaGp4bjJDWU1xQ1VqVjlPQWk2NzZ6VkxzK29a
            Y0ZBd2lTZmp0eTJaaVpzNktmK3lvQkZqc2V2LzVwT1RzN0FYWnVGUHZoR3NMUkxJ
            Y1RhQW5qYjFTM1gvVk0vYXA0UUlZQTdmZE5wVit2RUl0eVgwWG9zK0lYekxyQUZL
            Q1R0WE8xYlQ5aHFTV3VHMGxseEZTcUF2YzdCWG1vdUxFZ051aDNlTjI4eXFFSWZ2
            ZVFIbnV2R1RZRklNQmpTNitxZ09UMi80WDZJY21rMlQwZlpPV29zR2NqUEl4Si81
            QmdncXI1MTBxZitZSDQ3cDROOWVqRkhUazZzN29pTHlrYkUyQUdpZFJFM1JwbzNL
            T0h3THBYeVo0MG0wR2JSSVN4VkpRMElTTHZwY0RLTVNrakdSMkZYZmdsc1preHRa
            MUtaYUM2d2duaGt4NW9VbmtyMzhwbDR1dEJzZWp4RmtJQk9zajFJbXdSLzNYUVl6
            aVpzVTlNTWZjSFMvQk51eGVqa20wNm1YaEhsVFA3cXMrbWNSSUwrc0EvUXFCWEZ4
            N2ZQcVRMU0l4WmtGYWhPdE1NK2hYTEVQbjlzMFR5MXFraEd0TjJFRm54bjlOL1Mz
            OUphWnZ1ZzlJeVpiSktZcHhFTU9lU1hmM0hOdGRLR1lmWXI3dTFZeHBjLzZXQQpF
            YmhTcHNLaTJ4SVNvcDgvRGcvTCtnMGlNL01OY0JBb2taUnJPTDVPd3hjCi0tLSBv
            c1BHNkcxL3BrTFJEY29aWEUvb2J5enN4b1d4czhlZDMvNjNMSXhLZUFZCpk75ryr
            GMuPxOrW6wvd1UcXwnus9uHBxSRrH2fU8unuMqreFt3RfseCFIsC2V0P4rFdssHr
            8ZflgbbUw3vWaiY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T05:28:51Z"
    mac: ENC[AES256_GCM,data:7koaGEw+32SQklZDj3RT/hqqmWtEc82PMZo2gjBsT5wV/2HEx+qNQNAYF0idYPlKs7OKzf4vmaS/S1BzZdOSaeZc6TTTd0Ypaybn71B8Efx7nsNTNfI28nVaJtCMGa04KQMQaFIfuSBGZj00CIl5GP1HllTL+GfTxqTLCctLMUk=,iv:SOlID33EuG0TBr7Z2Q136AYtTsxHaJUxM74X5expql8=,tag:8iAl2uBdVovoyeW8u3YTeQ==,type:str]
    version: 3.13.3
