apiVersion: v1
kind: Secret
metadata:
    name: shoutrrr
    namespace: cloudflare-ddns
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:DwXzQtFXlcobfVGBDDddGLBdCOJ3DffbWuoFXDZ9g0ajEnFkd5gkKPve5ZQjyM7xTW2eHvplnlfD/B/UvMqAUSDbkDs7TkYXcJx+VMuR3Iw9qrMzA8wZDHH27utFKKN7zYG1I0X3+Xlob/ZBrFV3X3LTteB4g6FnA0Teof7e7EWD6SeNIIjL3dHxO/f46VGCVoFBQdqf69EDOR32ZQceOSN/e6pG+lOEi9soZtMvjA==,iv:tiLbUpejQsfxsbaO0GwK0gQwTL9u+fnAQ40QcvLswWo=,tag:e9LzKtbs+wCWIFov/Cfukw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDh2cTlzbXA2
            aFpMSy9haDIwelVyRitWUnBmMWpDcUp5a28rVVJ2ZVBUTmpHTGF2QkQ5K05FUExM
            WldabU5GSTZGWWNnekxjWXJmVlFla1ZmYWsrRWxCMGdIMklOSm9KVENUOExKd29s
            c1lQQk5pbUhpYTZNcGQrbzRjMTlJUVdqckozTDRPMkMxN1BCM01RbVNQa2R0alVz
            d2c4OUY5UWloaUVKcVo2RENOMDRrMUlNMGRScXJTclN5WG5HaVd3aDdOM3poNGtP
            bHEyZ25DNVZsU2lhYlE5TGpMUGxsenlsZ3AwVmNORTI3OEtCY1dZL2gwcFVnY2Z0
            Y1I2S0xpSXcwazdhaDh2ajVnZnpmN1E0ZUVwWmdYcXNrMUlQQk8rK1F5dUdCWlM1
            ckZnUGN2d3pmZUROck9xQWhCcmlOOVgxNUc1bllNRmhBZDFOK0lpTEUzNVAxVyt1
            V1lCNHpBVXZSQ3Z0R1AzWUxOSUlvSDQvWmlyRzgrdnFxaEZ6QTNGU0ZpSXFqRkxw
            QWdtY1hHekJheExpVlVSNjdKTVd4Yy9EQ1ZEc1JyRzVYUkxkNjZqSjBuOEtMMW5D
            OFJtb0Y5NHVxQzkwVjh1a2dzYlZUQlZHdG9YcDNXQ0JNTDVocjNrSFJKTFlsRlFH
            TkdnWG4rVlFoUkl3RDhLSmNoczNyeWNvWFJlYTVmdytaRmt3V1JFOW01VmhDU1NK
            SThRV3pvUDRLbFlkRVNjN0dHOWtjZmVldHpKUm1UUi9rNmhZdVNhTUZqWEd5bWlE
            Y01KelNTR0lEWjl5bUJBVzJpNVZLcU0wSVA0SFBvR2RIY2ptdWQ3V0hxMUFjc2hi
            QnZNbHZ6ZmhJeVFFNGJLcGFyTUhEMTNZZkk4cXhBV2daMGx4UmJWY3lia2IxN3RP
            VExZRFdydlA2WjVGaGJWWThhTTBrd1dEWERCaDlCUTNzS1dTQ3VJTk5jbTZMbkFl
            ZFc2ZUFxdjVidTY5UkxXM01lclBRMkcrYkF5cktKemZPdXBPMDF3YjJ3cHc5SHRH
            dktXL3AwN0RHWW9WYVFMU2RTSWRoQ21tcnJyRTQrbldLc1FPV3VSd1BvZUVxNTBr
            UjZuZVIrNkIrYVJvL0dlZUZnNk5PY1pFWHJwbDVJS1BiV1hLVHpxUHFmSm5YRUlS
            ajAzYTdtZG1BbnNwNGVlT1U0WDl1Zzl4T1hGQndkTEpldlhPQ09kbGlIS3N0a0JQ
            ZzZqSldEbmQ4K2s1a1B2YTlPZ1pQMnllK1RkS0xBRGhZRG5lVkR0ek9tNklrMnBk
            dGE5Ty9qd3Voa2hqVnhFKzJDbmQ0NXBRSXNJWWlaR0JYRDYyOXJWcW5ablBSdlhR
            MThiU0FESzR6VDlybEtSNVVRbE02cmNsTDR1bGR5U2Y4RFUwc2djYit0SVkzRHBi
            MnNFbzlKN3Y0L2NPbTNBd2pyY3dXRUNqcUcrTjNoRitnTXdhR05IbU11bnhHRGxB
            S1p2d3gvb2xJMC9QVmtNVUFzR1ordkFRYVc0a1IyT296bWg3LzF4Y2twbDdFTy9o
            Zk9jSXpiTUtSdHdhNGpQYVpqMUYzN1hPNXdsc2psZkpqenJjYnUzY29FV09OcjYy
            My9ZSU9hWGVrRHVRbDFkZi9LSjQzdENhaGJudUFPaW8vOVowMWRvMVQrNmRFZVVZ
            MHNUdGloRUFJU1FwMzR1OXZFa0JiMUtsYjF3UTdSY201NXowUUVrVHo5dVdVNjF1
            RTBOVno5REdYNldqV201ZVZTNEtoQmprWVNtQnZmcGpaMW1vWitUcWdxSnJ3WVN4
            cGZXaTZOZHFCTGhpcUE2dnB3MU9HNStwTm93dUNCcFB1aVZRUGhYZ05ZWXR4Tith
            a29nUFg2Umx2NThZYjhZUTZFVFoyUTBYR2Y2VTBTc3FXUHlMdnJVcWRpN2tYdGtP
            TGZDZXFQclZLRjNCazZaYUN5QVhJT0NnaDdLNWM2S2F1NkZzbi9rcmFLaEFXUQps
            NjVscitTdTNpS3pBalF6U1R4WThqL01QS2Z5clhLbkVKVzIvTnJqejZ3Ci0tLSBI
            OVc5VnF1NGxKcU5KSjRvTXgrcUwrRHhyS2RPeHN3ZzJ2LzAyR3FVNjRrCk4AbBIs
            1xpzkWm++SiJbB7tiukWM1RYKh1hi6tKA5uhSrfvvpbvMoP7KI2eC43nD+GGO1xe
            w/xv7JI5bhkEz2g=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T05:30:17Z"
    mac: ENC[AES256_GCM,data:+GOPhlb2Fk89a+jButzXiUn8utGdGK/X07pifJrls/tIDn13Yva4CL0xQ5SB+cIkJRtieFfsks2FGFzE/cgQX+1RjNX/F5F+or7c54a/CUJ33Wq/VF/v6APM5b3Lp1fiPqXamXtrijcUcAs+Eol0YVGybQNNKy5dY++dpZAOaDk=,iv:+T7/2Lb7HYlgwEzoK54ZEcVOxZjMQw3xNFeDkj9KMNw=,tag:3S8J7nrwDG3jW6lYYzfKRw==,type:str]
    version: 3.13.3
