apiVersion: v1
kind: Secret
metadata:
    name: wifi-radius
    namespace: wifi-db
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kc7KN5oXCyHJ/SA=,iv:bEfnSioXqX4b9IyJtk6lxQk4pGuv17Mb2KiNjv+Zsso=,tag:vVRKpGIOLOuBz/e9ybUKig==,type:str]
    password: ENC[AES256_GCM,data:9nhZzRMl8ZZiaT91LbZKWMzmhm6jCSc2JV4kdLc2r01XANLjRntUhZGPiSSn2qyXuNQ/U2QjXEHynXYL+pCPSw==,iv:OZTJMMYWYUGtMRCX0eOuAWRzjMZirbib3v1VqTYxEl8=,tag:QU0mKmWcSUNATRhZ5aDlHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEZVbnZnZVRo
            UVY5MGtUWGwrTHZwU2pBZmMwS09yaWd5QTNZM3FnYjVMb2I1cVNOQkNPUGNHaHUy
            ZU4wd0xTUWJMcHdhbU5YanI4Z3VPMVFPcnQ5S2J4TWx0T1RLdWpZbmgyand0R21u
            UkZZYlczbm9tT2hjOHZYb25iWkNSTEh3RkV0OFZDeDBMbjI1TVRWaExQTzRKd1RO
            S09TdjVQTGtBTzU2SWxqdEs2MUZCSHJLSmNSUHlOVm9vN0JDd05MNjcxNWNQaFcv
            eFRtQ05zWk9zMEgzeDNVelZGekQyY2pwRk1TV3ZJejJXa2cwalp2b1lSOGVrMDFX
            NHlnZEJ3Z1JDSTJBUlVLNUtvT3BreWp1ODZuQXR5VHhYRW5kVXAyRTAvamd6Y2xv
            a1NONHVzWm1CaXlkOE1EbUU3ZWdPTG1RRzR1a0k5Z0NWbEJwQWxDaVc1RWV2MmR4
            RXdjb2svSXNPSEVDNUlPOEFVZlZZeis4SkRNY1JETnRqR2VyNFFvUHk2UVY3V1Zt
            TjFMZStvODRLVk5OSVRsYnZMaGRmYmNQUytCKzZ3Q2lrL0pOV0ptMmpZUWpTeTVw
            VWlBR3dqTjE1R3BqMGRWU3R4R016bzNTUXVodDJPR2tyRW5SVFdTcFJkMVoyMnFO
            TklFNllHT3NmK1hZd2tKeTk3cXlvYnFPV1ZiS1BVMXRjN2pFSW1UbVk0ekRXRmdh
            UVRQMFZiVlZVcVdzTlNZd2F0Y0kyeE0yVGVValhpUFBzWWdHdjFqOURsM3RnT1Vx
            ckZZUUZWWGFpUnpNS3Z4aEp0Mm4wb0NDKzA0amovQnhmRlMxbTY2ZDl4aXNndHRP
            U1ZaSGorN1FITU1qN1J5T3Jsb0xVbisyM2RXMnJGOWZUWVdhRTRQME9xNm95T2JZ
            UTNlTWg4SmQ4SWZSZG5Hb01sZkRvWng4OUxrRmZjYWdkV2RUd1ZWdFc3MEJrQ25s
            bFQwRmszd3BXVmQ4UW8vdUhEMWRMMGxDM3FTN1BBRnNrRkRMWTVveVRSbXgxTURG
            QU9MbUpOVjhsdFpVbE4wNG5TN3RWNldTam9UWmU1dWxkMS9TUktwTGVJUE1SWXVk
            YWp1RDBkazR1L21oK01rcE00b0tnUU1weUx4MXdyQ1REbTJvU1UzUmtocmpRWGpp
            Y2p1b0hQQXhQRm9FQ1N4cFVhc2hqU0tGa3BGVWNES3k0TC9HQlg5NUJHVnVFTFh0
            d2hxKzdRdjNDbGVQcFJKVjBSdUtscGNzTXdGczhDU0x5QXk3MTh5MGxnd0pUQmxv
            WFZGZXZld3pQcEU0QWk2Zmg3UjNrNmtrbUc1Q1V6bU5ET2JUVENCMjFhVXRJdG5T
            QVVIbVA4dDJpVlpodkdBeDBiZ3Rna2srbVFKbzN1RHF4MUlSYXJRbkNrR1BXK2JH
            dmhPN1JnU2dwajVlS0x1NlVYOEdvQ0x1QWZadjJSSllwVEVWSk1PWG0yMEpvem02
            a0ZEK3pzd1pibkFUbUZreml4UUJ0YW4wK3Q4WFBmSDgrVGp6TnFXT0trNU1XRkVG
            Tk80enFRSTZndUI4RzJNU3hQbks0Wk9XM2QyNmpkSVhacExudkYyUlBxZzl5L0Vt
            amJodk9iaXRCajJpRmRVV0dPWjJkQ2RQV3hNc2lvelFtYWFkN2pIcHNsZjZIMFdW
            L2RBVmFzakcrOTRSdGdrZndpdUxZMUgxaW5UaU4rRFdmTkxuV1JRSmFqT1Y3Zldj
            UmlPNzdtT2tEcTVMYUF6Z0d3Qm1kTi9pWWFzVWlmYklKdHFDQlZuZ24zODZSelhB
            VVFqNTJHcU8xeVcyN1NENXFzdTNIMEQ2aVBlZTlIUWc5d2YyNTU0SUEvdHFONE5F
            VjNVbU9kZVZkb2FYTTJxdWJLa3hHVjYrUFAyMFFZdXdhKzk5aE1HVmtzNGFjcmhs
            dE1hd0YwQkxoMHAyYzM4TVRwSm10c1g4bGg5WEhnZE1hY2ZtNHdMSXpYaEhNZwpm
            VzFzQVN0UDZRc2haUStWSkUwRjFsdEcxSXFEbnNtTnUvWlFtTmRib3RRCi0tLSBi
            MzZSWGN4Ull6eGR2K1F2SktEM2xSZ3hGcmpUSVAzVSsvaTJLQVFyRm5vColrcBv1
            hzSkAD5aW00KEkNFA8C4ELugBE5dIW07036CxRPD70JUkc+h1ORGRy33CDG2tNnm
            VdLB3icy+pc0Qpw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T17:59:41Z"
    mac: ENC[AES256_GCM,data:cnAsQWLyVTav7tovxIX855PqasxwnobCOVoS8YikHUhdOiIVQAkMiP1Q0Hvei4MI6cbJy4BxC8vax8EwuByrqwNByN95fNEnmUw6e8pvI498PFLR1FG8NMnpS/7dXbs7LX3WuGYy5ZZ/fUmGnTOWTW7q4EuoFYeqrDLB1CzKndQ=,iv:jSwSoxsDSaU/PE3GyK8hte2F6CbwQpKWaPHbpMr66VM=,tag:LQBLULM+iYMDsrGHwmMGfQ==,type:str]
    version: 3.13.3
