apiVersion: v1
kind: Secret
metadata:
    name: authentik-ldap-wifi-outpost
    namespace: freeradius
type: Opaque
stringData:
    token: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDNQQ3BpcFQ3
            RmlSTk5HcWgydDNTV1JqdnBwVGFnMUhYeE5uU0dSblJRc2pGNGJkVW42TVo5aTdp
            dnpYRGdETmZmVzRwaGNRNExHc2d2R0VCM0hPaTVlNjVJNWdnL29iMVVGUjBJTDNk
            dkdtb2Izc2RtNE84alNpbWxJVTUvbnBUaEZxa1JyckZDME9VMy9NRm43QXJBVlZr
            cUpuMnVsNHFhbWRYK2FkWWZoQzVlNU5nTVYvcTl0Y05GMTJsMkhpZGFaUWYveHVU
            RktiS1hwNGRWUXVmaUNwSHJBUkNtaFFreDRYNmlrYnZhUHAvdmdSSDVFdXJDODA5
            ZUwrRi9SMFp1WWtkV3haSDVCeXNqOFlOZ3V4NkFacllUaWUxU041eHV2eEtPZDdz
            bDFPYlE3WVA1djVaZmZ4eSttSFRqa0I0Nk9LN3E5a01lclNrU0NqUktqR3RuUUhw
            YURnQUU4NENjR1NLT25SRURWWGJIU0t6ZkxxbFg5NnlMdHpiQWVuY1ZHQjR6VUFp
            dWN2U2I0VzZNN0tVLzlINjFJZmZ6ZmN1V0FLNmxzOHhxeVJVb2F1WlM3NURwSnQz
            Z3c3RWtheWJkcmJLLzF1UUtZZ0hORXkrQW9GMkZzV2VCVzBUZHFwalIrN2xLb291
            aEwwdlltT0JHTGhtOTBhaEwyRXJvZU9peTJxMlh2Z2xacm4xa2RVRStTdDBKTU5I
            bnhJYklJdVUyM2xRNzRkdFkwYzRjMGI2YXY3RU5JOXk1RDFyTWMrNWRsUFVxTjYy
            NTRuV2YrYS93WEpHQjVFVkw2ZVh6UER4dk43UlNxeXVST241WjN3VmxnWU1ZWjhL
            TXJ5a241Q3BqZTBWWEl6V2k1a0poVDE1d0VZZTkxWTNWb05HQkhXRXQzYU81UW9k
            clRjQmQ1VFN4N240Zmx0djkwRXRBZFF6cW10WkZRZStBLzRzVFptSGpodDNGUC96
            eU8vVE9EYlpRVjZ4SldnaUcyN1M0eGJ2cTUvc2FnSnRXN1RqcnJUcHpJZHJlbmFs
            c1dYK0RrclhvYVRXKzBCU3FjaXA1TWpCVHAwVlNONWczQ2hoMVp1SmJoS1ZFTHJu
            bGpWTDh5Y3ZmdkpHQkgwc2w5MXNGa2hudFRFamU0NVNyM05CbWxQTFNMeUZFVWFT
            QktERC9oamVaZ0ozYXFzZzNXSnZrck5VSnYzMURQK2x5bjAzVmVNQk1wUGxsVCtO
            aWJMdlFFSHk5REF6ejhlQVo0Y1d6NXZBdGV2WnR6T3ZEWXYwd3ZUdkJWT0J1TVlW
            d1pTOGx4VzJkT3FjZ3FieTFwZmlTencxWlFZVm1jZEE4Nis5UVE3M0ViNC9nVUJl
            NG9nK09JaDZsM1JkTGF4TzdwUFhnUUhCYXpYU2UvalQwQ3lrdERJQVkydG02Y24r
            OFVobTVST3Fya2VRaUNtR1FIaHBLZ2NnQWdhcjFoVWtkYWdaU0g2Uk9DN21qZ2Vi
            NXBndzBXVTJSWEcwcWVCYlB3dFVhUnNHWmZOVmFJTlE5YnJ6VzU4djE4ZlJsSGd2
            bm5tck5Pcnhvc2lYQ2p1U0NFNEk5SXhvUFB1RGpnMDk5NHdHTERLM2wrTHBJQkdl
            UW9kenJWZHltcTN0UlBtbWN5Vi96N250eTZkMThWZFd5dVgzYUllVnV1eTE5ajJB
            N1JUK2FlUUlTSVFKRFhpMFhleWlBK1c3OUptT2c1ck1MVVUrQm1MK05EQ1kxSGc5
            Qm9ZNVdkbHlMVGFDbjlDQ1U0T3drZVFaeHF5U1NDcFVoVi9XVVQ3d2pOMFgrTUJh
            RGJtYnlENXVTUFBvd2dNVmc3dDdpdUJhTzRHcHAycms2cFR4SU9WQm5iN1VRbnBY
            NEpiTUJJejFRMUlZb0Y2a2dEYTRJSUd4SVdkVFVEazZiRXRaMk9INUgrVEh3eXZy
            OVlLY0tNbW9LbzFwdTdMdXNTWnlhM08vMm5ObjVQOWFpQ1BYVG9FWEpONXJMUQpp
            RUt6OHFTdVNyUlcyZUNSMFpiRXpPRi85MkZ5TmZIWEFhWUtQemZSZm80Ci0tLSBC
            cmJWY1dHYmJScUgzNUhqbTA4SHVGMll3aEN0OXRMYjd6Z0d1eEhYNjZvCsG0xt0O
            jJHBKyeDrtk4xCNaN/DjT6hoo1Urci3KzS/iQt9dVMpdzR6l79BJjAUYvBkgVF+s
            gyBd3YGsgirdYos=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:31:22Z"
    mac: ENC[AES256_GCM,data:qTiI6hlLmduHGyIQhfaPbKbznp2kgcLaDXRlU+fY2r2mZU3SgCpKPuF6m6Zx80BL/tDF8mhuQzDmCTYxbo5GE4LjPcHLtG3IWX9pEDyiGCUQV/UIclH05FJZlZ/iv4y/htZARHZY2YWpHZKTg+S+4DB/kt0wMyga9uCmYSKqgQU=,iv:hYdBhgZ/DS75zhx5NUM1hWkiu6ywPP9GP9GIFS8TZv8=,tag:S/UEgfYQDxHbo7XsareyVw==,type:str]
    version: 3.13.3
