apiVersion: v1
kind: Secret
metadata:
    name: freeradius-db
    namespace: freeradius
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:3/YqhrwCLAbEWTo=,iv:f2rfovv7gWXffMraynct+s4xopH4WGO91IepdJDsMGo=,tag:9iU5p2P49834Ib8xyplxEw==,type:str]
    password: ENC[AES256_GCM,data:5GhvTFPSkr4Mrbz7OL4BshXb+FW/tAUB143ClMaerWUgYltO1pivvzMvsxtCLVL3szslhLJmVM8COrkuxRmhQA==,iv:6iAEGsZ6WuV0zriQFt8B2z6seBD5Sv0Jih7lrGSK4xo=,tag:m2iE0QuESHSBxnUX6FSLqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFBoak9EQk5G
            RTh2NXJLK3VCSkNuRUQ3VVdWNURvcit6Q1pCcGk0VVdCWU9vMFdHVFZES2c2NUNB
            QXFCSVRXZ0p3OFdwMDlVK0ZvVE1NU1FmczVxMVEwb0NWV1JEZVcwV1BiL1dYeFEx
            ZUlzalk0RlduVStQTlRCaENBcjI4aWtDeS9EdUoxTUg3Y2pDSzBPTkxVcGpnMW1y
            QUZ4bnJ1M2FKaWE4YU5jOTZFVS94d3VoMnd5bWppVTZPV2hWaC9rNVlSZGFDT2Mr
            ZU5xRVpYSnZDWHFzSFozNHZqaXhPVHNhbXBXeDRCZVJrbmVOck1CSFpFbS9xZkJ0
            VTZOL0U5bGJRY25wKzlHWFZJRUFMUFlnd2xlUEloOGVZazZFZ090UXRDSVZhekJ6
            T0gxbzhBQTVhOE9DN3dQT21SM2JKR2FMT2VXaEphZG5xSTAvUFVlc1c1QklCeUpq
            cE1GNHZoZ2xoZUdxcmxtbzd2T1l6Y1B6SW40SVFCcmttYXVJWmMxaVJEYngvUjNS
            VmxCU2dTcjA5QlVpeGtITDVHS2lEMmlIOVg3YmVNTXRQRm9PalgwZVpTQVd4K1dS
            RTdjbllGQTBNVGpjVWFZTUs3OHdzU1F3anM4WENuQ0pQTnVRZitXQ0ttZVp1dVl3
            cWkrRXMycUsySFNDaU92Wk5hTjk4eXJlYTc4N0RvZ0I5UWtISStCd3d2YXlaaTlB
            RktjeFF2bkc1dGV6aU9LMXFmaDFTWG9rcTdvTGJ4QkNCWkZXSjJtVXBFc2NUVlBv
            aTF2V2dMT24rdWtZejB2aDAwaDFKT3NrRnlsUzdWSVM0NmpUcXY3THRJakpiT2ds
            M21IUXdyOWRTcy9TMDZIaWlLVXBhc1RxVDdSbVlOMWxXazZnblFoRmF4YWs1SlJx
            aGx4WCs5bTduSmRUQjcycnYvTHcwRnB4bFZQbG5CRTZDUi9ialJzeFFNSU1ra0xN
            VFAzWjViUmJ0eW1GTEhKMERDL2orZERBZ1Z5bUNMT3p1YzJNT3JDOXdtTzJIK1dG
            NklWSEczYkErcEV0N2JNTkRpVzdnNjR6R0Vqd3ZLVGUyOEQ1UWl4SnFBWnVnUTJX
            K1RKeHZDL0p5YzZNaGdNZ0gyL2N5OVp4ZitFMkp5RkhwQVZCK2JnWHBZbGg4U3h5
            UnpFcHpHbTFuUlYrbzMxb1N4c05RR3dhZmZHK3FYQm50U3JPTDBjdmx6ZWY0cU96
            Q2tTM2dwVy9BZkgxYlM1SjdoL01LQ3JOWmZRU3VZY3Z1VUkzSVd5bjloOVNRV2U2
            cUJES01QUlREM2xRdFB3N2ZxcG9vRjBHaDBwRlVrY2dkZzRYc0RiaVhzZ3I3eVFo
            b2YyR0FaM2kwRTE3TnlwSk9Xcm9tOGEvRUo2VDBSaURUaU5KUUlIVU5rVzNMNWFy
            cVIvUEFwZ1R6NUxjbGUrMXp2dEsreDhmK2toOWdXSUszUFhGYVI5ejloVnN3cnpN
            d0ZtRVFYeHBHZkc3YWQ5NVpnMHhrbUN2L0MxOHNZSllLU0U3Yzh1V3VDNTVlSVg3
            aDl2QXA3b21VRVJYUEViakJiQXZEbjR4WTJjaEx0aWhFdFAxdjZBaVRaejQ5WlU1
            K0RGNjQ1REpiWmNocHhEVTNwL0RZZ3dZRkIwZFgrd284YmhaVmlzdlpOSjFXa2JX
            NCs2dHdmS2FDbUJaa2JoL3JjUzE3TlAxdXZIbnE3NldkSUVrdjhNOGRtNVJpcE4r
            cThuQk1CK3JLbWk3MDMyL2R4QmNBVnFPbHR4TTlPQi9jVE83TEdGeERWS2dWYllU
            T2NINFpLdmdURFc4VkZPZXhmdFNibE01VG54N3c4eVRSUEJHTzVLUGZnTG5iMWFJ
            cVdHZ2k2bERYeEdhWEYxdkdkbXVRVXhWZEtRMjJhV3dFUjRXNVRnUElqUjZ2aGpW
            R2NjTE9Hcnc2Z2JGT0ZUdWhRblZmN3RRRzEvb1hMRmRpdHJtMkF3TlVFSVNFdwpo
            ZnJlc2V6T0xyL2xiWlhWZlVjcXQ3aG16ako1OHE5NWduMWZYWXlnYlpjCi0tLSBD
            NWIwa04rSUhZKzJSaUh1V3VqeHlnSFdhdXVNUDh6K0k3d0EraGdXeFlnCvgLZm6K
            wogdEGXYE0QPkycpGkZUPEJ6P8q7J5VbJQhDtnqKziXWGqHMR/DcrAEqBNIw4P5j
            Uat1NdD1Akvwt70=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T12:06:19Z"
    mac: ENC[AES256_GCM,data:EZuunQO79/0KhYtyIMewoifDtHewKg+w+RjTxqodMRVg4Lgd6Mt6sR+72Zr7LhXpzpI+1uZBdOrAsSt77Rf8Q+2+7A/vcp84Z7aV+JPC/jxc99Y8U00yyyIIX/+gUOopCQpHuZKL3sasTpNtFDxThdNWLQDLgs41zT3ezo1zCYk=,iv:65PMxp8QvNrAmEtU136kt22zfnw7RkWzatsCMUgyfQ8=,tag:kmA2lEKwyx3PDoqILohuyw==,type:str]
    version: 3.13.3
