apiVersion: v1
kind: Secret
metadata:
    name: freeradius-secrets
    namespace: freeradius
type: Opaque
stringData:
    openwrt_secret: ENC[AES256_GCM,data:IbaTqLl6KP3NMCHdsQlNpHJTCSQOMIxUj7wLsCGGhT2feNbx02VLkA3uGqUTYqhX8lD8U9sHJcSa+p5LThbX/w==,iv:LjeoTPPbQubaUOC1QZUHk2SoH6yWdqiGlmgCA/nbZBA=,tag:4Nkt73BFJNiSJSEvZTiQeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFFJY2piZFhh
            bXBEM0hST1BydVVLZGRTK25TTmhKWlFCRWdaQmk4aHlLQ1VHcG9DWmJ1bExxZzBy
            aWdSclBUY1RuSTdVd1lPTG52Zkt0Ym9hOUFDUkRNY2JQdTRNK1dpc2dtTVUxcWpv
            SzFhcWNHdFluY2dkN1M5MUtwWUJxZWd2NUd3Nm5xbTdJRWpRY3hBcjM0dThFcW1q
            SkZnZFlSVzRveXB4WnpjSDQ3M3dha2k2MFdYU1ZSYzhyejkrUUQ2QTlJY21LTDh1
            OUhzOEZYUXExdWwrck9Ld01pelJnVFU1MnFTY1FkVnNiRGE0T3dYMjJJa01ETCtz
            NTRsaHVqK21odERpd3NyMndTRTNCbEkySlNUVllUaFR6UlE4VUZVZEZwM3hIem9J
            dW1QVGFmU0hKd0JzdnBhUFVDYS9qT21sdFRFSWdpSkNLYXlnSG1GYzl2YytuSE1N
            OG94b3htVWQzLzdOZ3NJelJJTmgvdXJoQlJ6Kzdia0tYNW5PM3p1cy9iMkRoZ2ZT
            WU1sSGRyUWsvUXZ2OXBMbEpHNGhYRDM1TG1RQTNQZnoyclRwMWNNaSttdjdhQWor
            d0l6UEVydG5kNVIvdHh1Q1NsS0lzWHd4SVpKZjljS3VLaFNhZENzMExDKzB5NHJO
            aFhhTVJ1NWl0bFBER1BLVjRiSHU2MmExS1BDazlrR2h0TEpkcHF1QTZ6bFh1VFFt
            d0RyQUJlV1Q4S0NUSXZJZ2VmMjRnaG1BdlVYcDkxQjBLTUhOR29Cd1V6bkQ4dmJD
            TytKSGpUUkxvRUZqb0lFNkdJODhJdmF0N2dCSlNwcGpmamlSYTdUVmNWMmdnVEZy
            VWZSUGpQUFdjTFBFcnIyRXo0RzRrVGE2TGdBcS9WTG8raCtxbGZiZGJybHhta0lw
            RVRGT2FuQ2xFWGxvWFBZb3ZwSVkyT3E3Ulk3aG1KYkJTQ3I4d3FJQVdFb2dtbXZM
            Nzl4eGgwR1NueHduQnQ1czd0cWpoVEg5YWIyaFcyUUhMRVdEY29HZFRpWmtMd2NB
            Z1hvb0lCK0FIOE04N2o3WVh1QWFOSnJJTXNXS0gwUXhkT2pEMWFMRmE1K3g5eHdo
            SHprZXpCMk1YV1duT3ZxWFdlb1FDSm1BUmh6Q3QvNmtyYndpWE9oUEx3ekw2dVYv
            Q1NhZFBZVG9seHVTWDdlYlU2WUUwMk1kaWh4R2xMblpKSXpOdGRuVGZ3R1RSYjk4
            ZW0vRWRMMXlLVmg0UHA3MVJMd3FRQjhtMW1vYnhPT29rbUJ2SXhjSXZDUzYvdCtV
            U2tkN3VmVlllYlBrUkZxUWdOQTF4SXFadHRmTmNVcG5IemErcDV1RUMxQU0yY0pK
            MGQ5RUJUWU1mUVcyL2hMRTIrSE1jd2w3YVNHVjBMNXJkT3JadktGNi9ucEVpeHFQ
            aThJQkRiNjN2S0lBWitpU1djNmJ4a3JCVHc2SDZ1WDRoMlpuREZRcTlpWEJIN2xH
            TWZrdVNpZHRidUNuQlVEVzFJWG93SDN0STVZcEt5R1Y1TWI5b211eS96RWFUblNO
            VHExWkRUQjJsRnZYV0xBZkpEY0szaUhXWFVKL0JmOGxrUGtIc1BYbFpiOFdOTzBV
            TlNPTUNzWWJWd21DcVc2TkFHV3JybjdiVXp2dlFqZXFicWxHb3VmMkJnRmtLUC9w
            Yy9TVTQxRW81WlFPbUliaHFGVXZzY0poeVNsVHArQUc0UTVwc3RpMnQ2clQ0cHE0
            djdvdUhUOFA4TG4yTC9scGIzdCsraE5xNCsydHFseHNTQmxGWFo4WDk4bWttRkQr
            NVd4M2xSVFJ3Z2NKWTN1dmY4azlOSys4S3FrblF6MDllbFVNSGQ3SHgvaTF4ZzY0
            R2w5TWV4WC9iL3JYSmp2WTU3U2RqR2ZnNllDZE9XV3M4OXBRMXQyOXdVcU9oWVFa
            eHA3WTZtNURTSVo2WmFvQzh2dk1LdHpyZll4WEl6ZEJwMU40Uy9QczEzaDdDQQpE
            Y0dLVEMzL290R2ZSOUp5aXprbDdva1c5RnpQazMvOHhvSmV3ZkRxeTE0Ci0tLSB0
            RFVyR3V2RkJpVGhKc1g5VnFMMXJXTUJQVEJIYVBHSlptYUFEeFlBTmRVCjrC6wRW
            tPbds9ZfhLKpvF8xCh4rHTfIvZ3V3VwxmZEpqnejlNXA5aKwR7hbEwnPi1cR7TUE
            FIDyjA0Iqko3gXM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xzy9y0fqeyzp0s2yvem9e2ycc9fr7lmjp44pz645zs3y0xjy70544j7gh6h0yd0lwfs5ee6a46m4lldhg4z4e0ugdst0gkctarsqhwe9qmk5k4fevv8hcpra3ggcjdnedvcvcdvpqaj9w4ujs4zxkxa9g3m5q6lpd8q5a6esxgxr70f4xcfrxgp3apcwz2eck228293efw2rjj200pkd0u3njgtmwpym5lt2ryc0wgsm75p7m4tp795jetlce857t2dtq4eklpqsyeppdejkg27yj4xr2ftnawcsgm48pytpgwatcpmhk7exdjfvcgamf65mdj7mx4a0qcaxlhf39c39v5mzyprh0xeszsg2nzcr83fkp3ug4n07y7pp9axr89vhjhlv8ns0yn7hyav55zy8u7qnmtvfep4hg9umw9a0j49yhtcpz2wk8rx5wxh6sgw59ar4h0n8apdrc5nwzf4f4xseufg5r6ucz9jh533ykmyw0pjur5etfn22td63sa2e29cdrsyp7cs6x73m6ylcxv23vdu5yc4g7wrn3v6xp3hn4ku94f82s4v0jyy6a9jrsa22448n5mukuqgcna2f0cr24hup5cwp5f4wmzakx42qleetl7q295yyx95wx9ch9ut87j6m7ksv5fhzy0c3j99kcyvlzf3545xxrynn2tel7nr483p4vveqq37n8pmzx645axx9wadmd75y4g5mchtnqvrx5xyag2csg4wzg754pssy2xyfkd8vetr40m9cczr43cyu2d8wvv0um74w2rfc4tnc9h0uww8r69u23q9d09zjhjd28skdj8w0zpl50w3szt5satkx4g8ws282rxl6g949hhn46285xuuwv684mjshnygcwynehlry8859q77nzj8qpq9n4qt5lgh3y0vnhnffcvzfsznt75w8jpgt93ytefv03xfgywret4z3hfr3tfr8ndcpywwzmp6garv6z3lqwkr6juzjwu77wwc0zs4zn2lg3fqphqgde3rwvwfq2n2yj94twvdr9th589n3fvj2999tv8lz9lhmd2dxj3ymrarmxncrkgm3wcucyuskhdgcc747zwrvx5zucmu0rnms5522mzuw5vghe6pyvhn0xk0t3zp9r2slaxvhps5hv8v8tfnds93n35nya9eyky3hchaz4yf4gvf8zlrm8dwxe75mgxx7r8kec89n43zhwqsvpyypr9q229l8cdq423def4jtfql9504u3283kf04wjef6v2eqlqyskyavhrc33v03cwdpyyyg7uzgc3jjqqgu5zauytazux95dajrlr2eff4w99mxq3esxmx8uper5qv9gqs7f77rpzam82nj8k50plvg8jg3zs00f3alku3cvxupwml5gd6ddaflsrnn03yg20x3vjyvcfajkrns7qssfs4eryzdpslsmhxez62t7rc5w7g8mjqxuxj9fvaas0lw8ru4j4c88h5tujenqtrpwfdmkdnkw39vjxyyjfazq2egx2l324ftmf6nd3gdmnw3s970yrzz5rpz7g5t4p65lsnhzlqqklv2gurllpt47s4d0pq3v6vc75qnrrhgzjph63uwel4gmfde2zqanpk9xx8sfgj09dfdspf8stllpj58ny2kp2phfhhg9d3s6syx0ykm7vrt4984tlh9j3wzfxht5eez3fxpf3ztnuaj9y6yd9f85k0tmj40pxhpz6h0v3273p9qjrqwrj5emyj5tymc6rhgv4e432yy095uufc348tedgtfxzcswu07tqydqp5wjzk4yjuzpel7jm5dt36hkggkg373y9rsj64znf77enmkrmhj3xpez0zncyemn02x80m8kr4kh0wxqc4hnzsc8z93fxwkekt6gardhyszwj930g7awctv0vet43xa27jq7cqtusxpyazrxwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T17:23:04Z"
    mac: ENC[AES256_GCM,data:kH8t48bSa2lcM8s7ZCA+6//08LYCLt2UmD3V3wqRgGnKHfE+eJmhTt9NKCwYS8hoxJoN7NRcq7pbjwdRlcvyPP99vufrf+Z6RNxtshKHuSEUPlzt91Iao0+B0L+tofl+1rb+bRq1LOg9TOqASUMjN8z7DtTPv1py2DwIJVHMwYg=,iv:nHfC1FM3hUe3ZBBTMpWlVVR0M2HBMRHheKbn7dJrbNg=,tag:f4fphVnW5VhY7uZPXxRnGQ==,type:str]
    version: 3.13.3
