apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-ldap-wifi-outpost.secret.yaml
  - freeradius-db.secret.yaml
  - freeradius-ldap-wifi.secret.yaml
  - freeradius.secret.yaml